# 服务名称
spring:
  application:
    name: coderchen - springcloud

# 服务端口号
server:
  port: 10000

#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    # 是否从其他的服务中心同步服务列表
    fetch-registry: false
    # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: false
  server:
    # 避免eureka自我保护机制，导致服务停止之后，eureka不剔除已关停节点的问题
    enable-self-preservation: false